Repository knative-sandbox/scaling-group, pull requests merged in 2022-12, with the labels that each got.

#1 Update working group sponsor
  OWNERS
  README.md
Labels: kind/cleanup, approved, lgtm, size/M

#2 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/M, skip-review

#4 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#5 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, skip-review

#6 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#7 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
